llm_configuration:
  provider: lmstudio
  planner_model: qwen/qwen3-4b-thinking-2507
  executor_model: qwen2.5-coder-7b-instruct-mlx
  provider_config:
    base_url: http://localhost:1234

preferences:
  code_style: prettier
  max_line_length: 100
  use_strict_mode: true

project_settings:
  language: typescript
  framework: null
  test_framework: jest
