llm_configuration:
  provider: lmstudio
  planner_model: qwen/qwen3-4b-thinking-2507
  executor_model: qwen2.5-coder-7b-instruct-mlx
  provider_config:
    base_url: http://localhost:1234

preferences:
  code_style: gofmt
  max_line_length: 120
  use_error_wrapping: true

project_settings:
  language: go
  framework: null
  test_framework: testing
