custom_instructions:
- Focus on clean, maintainable code with good test coverage.
- Prefer explicit imports and clear variable names.
- Always include error handling for external API calls.
ignored_paths:
- node_modules/
- .git/
- __pycache__/
- .env
- '*.pyc'
- dist/
- build/
llm_configuration:
  auto_switch: true
  executor_model: qwen2.5-coder:7b
  fallback_enabled: true
  mode: hybrid
  planner_model: qwen2.5-coder:7b
preferences:
  auto_index: true
  default_mode: peer
  privacy_mode: false
  search_enabled: true
project_settings:
  framework:
  - FastAPI
  - Next.js
  - React
  language:
  - python
  - typescript
  - react
  - go
  package_manager:
  - pip
  - npm
  test_framework:
  - pytest
  - jest
