custom_instructions:
- Focus on clean, maintainable code with good test coverage.
- Prefer explicit imports and clear variable names.
- Always include error handling for external API calls.
ignored_paths:
- node_modules/
- .git/
- __pycache__/
- .env
- '*.pyc'
- dist/
- build/
llm_configuration:
  provider: lmstudio
  planner_model: qwen/qwen3-4b-thinking-2507
  executor_model: qwen2.5-coder-7b-instruct-mlx
  provider_config:
    base_url: http://localhost:1234
  auto_switch: true
  fallback_enabled: true
  mode: hybrid
preferences:
  auto_index: true
  default_mode: peer
  privacy_mode: false
  search_enabled: true
project_settings:
  framework:
  - FastAPI
  - Next.js
  - React
  language:
  - python
  package_manager:
  - pip
  - npm
  test_framework:
  - pytest
  - jest
